/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gwi_ndk_JniUtils */

#ifndef _Included_com_gwi_ndk_JniUtils
#define _Included_com_gwi_ndk_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gwi_ndk_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gwi_ndk_JniUtils_getStringFormC
  (JNIEnv * env, jclass object);

#ifdef __cplusplus
}
#endif
#endif
